# -*- coding: utf-8 -*-
"""Copy of Final_Crop_Recommendation_ANN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pijyGZ2rib1e46DKF9yZyrrZIS1-JrkK
"""

from google.colab import files

upluploaded = files.upload()

import pandas as pd

filename = next(iter(upluploaded))

df = pd.read_csv(filename)

filename = next(iter(upluploaded))

df = pd.read_csv(filename)

df

df.head()

df.shape

df.columns

df.dtypes

df.isnull().sum()

df.duplicated().sum()

df['label'].value_counts()

print("Number of crop classes:", df['label'].nunique())

df.describe()

import matplotlib.pyplot as plt

plt.figure(figsize=(12,6))

df['label'].value_counts().plot(kind='bar')

plt.title('Distribution of Crop Classes')
plt.xlabel('Crop')
plt.ylabel('Number of Records')

plt.xticks(rotation=60)

plt.show()

numeric_columns = [
    'N',
    'P',
    'K',
    'temperature',
    'humidity',
    'ph',
    'rainfall'
]

df[numeric_columns].hist(
    figsize=(14,10),
    bins=30
)

plt.suptitle('Distribution of Input Variables')

plt.tight_layout()

plt.show()

crop_means = df.groupby('label')[numeric_columns].mean()

crop_means.round(2)

X = df.drop('label', axis=1)

y = df['label']

X.head()

X.shape

y.head()

y.shape

from sklearn.model_selection import train_test_split

X_train, X_temp, y_train, y_temp = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42,
    stratify=y
)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp,
    y_temp,
    test_size=0.50,
    random_state=42,
    stratify=y_temp
)

print("Training data:", X_train.shape)
print("Validation data:", X_val.shape)
print("Testing data:", X_test.shape)

print("Training labels:", y_train.shape)
print("Validation labels:", y_val.shape)
print("Testing labels:", y_test.shape)

print("TRAINING")
print(y_train.value_counts().sort_index())

print("\nVALIDATION")
print(y_val.value_counts().sort_index())

print("\nTESTING")
print(y_test.value_counts().sort_index())

train_data = X_train.copy()
train_data['label'] = y_train

validation_data = X_val.copy()
validation_data['label'] = y_val

test_data = X_test.copy()
test_data['label'] = y_test

train_data.to_csv(
    'training_data.csv',
    index=False
)

validation_data.to_csv(
    'validation_data.csv',
    index=False
)

test_data.to_csv(
    'testing_data.csv',
    index=False
)

from google.colab import files

files.download('training_data.csv')
files.download('validation_data.csv')
files.download('testing_data.csv')

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_val_scaled = scaler.transform(X_val)

X_test_scaled = scaler.transform(X_test)

print("Scaled training:", X_train_scaled.shape)
print("Scaled validation:", X_val_scaled.shape)
print("Scaled testing:", X_test_scaled.shape)

X_train.head()

X_train_scaled[:5]

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

y_train_encoded = label_encoder.fit_transform(y_train)

y_val_encoded = label_encoder.transform(y_val)

y_test_encoded = label_encoder.transform(y_test)

for number, crop in enumerate(label_encoder.classes_):
    print(number, "=", crop)

print(y_train_encoded[:20])

import joblib

joblib.dump(
    scaler,
    'crop_scaler.pkl'
)

joblib.dump(
    label_encoder,
    'crop_label_encoder.pkl'
)

print("DATA PREPARATION SUMMARY")
print("------------------------")

print("Total original records:", len(df))

print("\nTraining records:",
      X_train_scaled.shape[0])

print("Validation records:",
      X_val_scaled.shape[0])

print("Testing records:",
      X_test_scaled.shape[0])

print("\nNumber of input features:",
      X_train_scaled.shape[1])

print("Number of crop classes:",
      len(label_encoder.classes_))

print("\nReady to build the ANN!")

X_train_scaled
X_val_scaled
X_test_scaled

y_train_encoded
y_val_encoded
y_test_encoded

label_encoder

print(X_train_scaled.shape)
print(y_train_encoded.shape)

import tensorflow as tf
from tensorflow import keras

print("TensorFlow version:", tf.__version__)

import numpy as np

np.random.seed(42)
tf.random.set_seed(42)

model = keras.Sequential([

    keras.layers.Input(shape=(7,)),

    keras.layers.Dense(
        32,
        activation='relu'
    ),

    keras.layers.Dense(
        16,
        activation='relu'
    ),

    keras.layers.Dense(
        22,
        activation='softmax'
    )
])

model.summary()

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

early_stopping = keras.callbacks.EarlyStopping(
    monitor='val_loss',
    patience=12,
    restore_best_weights=True
)

history = model.fit(

    X_train_scaled,
    y_train_encoded,

    validation_data=(
        X_val_scaled,
        y_val_encoded
    ),

    epochs=150,
    batch_size=32,

    callbacks=[early_stopping],

    verbose=1
)

best_epoch = np.argmin(
    history.history['val_loss']
) + 1

print("Best epoch:", best_epoch)

best_val_accuracy = max(
    history.history['val_accuracy']
)

print(
    "Best Validation Accuracy:",
    round(best_val_accuracy * 100, 2),
    "%"
)

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))

plt.plot(
    history.history['accuracy'],
    label='Training Accuracy'
)

plt.plot(
    history.history['val_accuracy'],
    label='Validation Accuracy'
)

plt.title('Training and Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')

plt.legend()

plt.show()

plt.figure(figsize=(8,5))

plt.plot(
    history.history['loss'],
    label='Training Loss'
)

plt.plot(
    history.history['val_loss'],
    label='Validation Loss'
)

plt.title('Training and Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')

plt.legend()

plt.show()

print("TRAINING SUMMARY")
print("----------------")

print(
    "Final Training Accuracy:",
    round(
        history.history['accuracy'][-1] * 100,
        2
    ),
    "%"
)

print(
    "Final Validation Accuracy:",
    round(
        history.history['val_accuracy'][-1] * 100,
        2
    ),
    "%"
)

print(
    "Best Validation Accuracy:",
    round(best_val_accuracy * 100, 2),
    "%"
)

print(
    "Best Epoch:",
    best_epoch
)

model.save(
    'baseline_crop_ann.keras'
)

test_loss, test_accuracy = model.evaluate(
    X_test_scaled,
    y_test_encoded,
    verbose=1
)

print(
    "Test Accuracy:",
    round(test_accuracy * 100, 2),
    "%"
)

print(
    "Test Loss:",
    round(test_loss, 4)
)

y_pred_probabilities = model.predict(
    X_test_scaled
)

print(y_pred_probabilities.shape)

y_pred_encoded = np.argmax(
    y_pred_probabilities,
    axis=1
)

y_pred_names = label_encoder.inverse_transform(
    y_pred_encoded
)

y_test_names = label_encoder.inverse_transform(
    y_test_encoded
)

print("Predicted:")
print(y_pred_names[:20])

print("\nActual:")
print(y_test_names[:20])

results = pd.DataFrame({
    'Actual Crop': y_test_names,
    'Predicted Crop': y_pred_names
})

results.head(20)

incorrect_predictions = results[
    results['Actual Crop']
    !=
    results['Predicted Crop']
]

incorrect_predictions

print(
    "Number of incorrect predictions:",
    len(incorrect_predictions)
)

from sklearn.metrics import classification_report

report = classification_report(
    y_test_names,
    y_pred_names
)

print(report)

from sklearn.metrics import confusion_matrix
from sklearn.metrics import ConfusionMatrixDisplay

cm = confusion_matrix(
    y_test_names,
    y_pred_names,
    labels=label_encoder.classes_
)

fig, ax = plt.subplots(
    figsize=(14,14)
)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=label_encoder.classes_
)

disp.plot(
    ax=ax,
    xticks_rotation=90,
    cmap='Blues',
    colorbar=False
)

plt.title(
    'Confusion Matrix - Crop Recommendation ANN'
)

plt.show()

from sklearn.metrics import (
    precision_score,
    recall_score,
    f1_score
)

precision = precision_score(
    y_test_names,
    y_pred_names,
    average='weighted'
)

recall = recall_score(
    y_test_names,
    y_pred_names,
    average='weighted'
)

f1 = f1_score(
    y_test_names,
    y_pred_names,
    average='weighted'
)

print("FINAL MODEL PERFORMANCE")
print("-----------------------")

print(
    "Test Accuracy:",
    round(test_accuracy * 100, 2),
    "%"
)

print(
    "Weighted Precision:",
    round(precision * 100, 2),
    "%"
)

print(
    "Weighted Recall:",
    round(recall * 100, 2),
    "%"
)

print(
    "Weighted F1-score:",
    round(f1 * 100, 2),
    "%"
)

model.save(
    'final_crop_recommendation_ann.keras'
)

model.save('final_crop_recommendation_ann.keras')

def recommend_crop(N, P, K, temperature, humidity, ph, rainfall):

    # Create a table containing the new input values
    new_data = pd.DataFrame({
        'N': [N],
        'P': [P],
        'K': [K],
        'temperature': [temperature],
        'humidity': [humidity],
        'ph': [ph],
        'rainfall': [rainfall]
    })

    # Scale the input using the same scaler used during training
    new_data_scaled = scaler.transform(new_data)

    # Ask the ANN to make a prediction
    prediction = model.predict(
        new_data_scaled,
        verbose=0
    )

    # Find the class with the highest probability
    predicted_class = np.argmax(prediction, axis=1)

    # Convert the class number back to the crop name
    predicted_crop = label_encoder.inverse_transform(
        predicted_class
    )[0]

    # Get the probability of the selected crop
    confidence = np.max(prediction) * 100

    # Display the result
    print("Recommended Crop:", predicted_crop)
    print("Confidence:", round(confidence, 2), "%")

def recommend_crop_top3(
    N, P, K,
    temperature,
    humidity,
    ph,
    rainfall
):

    new_data = pd.DataFrame({
        'N': [N],
        'P': [P],
        'K': [K],
        'temperature': [temperature],
        'humidity': [humidity],
        'ph': [ph],
        'rainfall': [rainfall]
    })

    new_data_scaled = scaler.transform(new_data)

    prediction = model.predict(
        new_data_scaled,
        verbose=0
    )[0]

    # Find the 3 classes with the highest probabilities
    top3_indices = np.argsort(prediction)[-3:][::-1]

    print("TOP 3 CROP RECOMMENDATIONS")
    print("--------------------------")

    for rank, index in enumerate(top3_indices, start=1):

        crop = label_encoder.inverse_transform(
            [index]
        )[0]

        confidence = prediction[index] * 100

        print(
            rank,
            "-",
            crop,
            "-",
            round(confidence, 2),
            "%"
        )

recommend_crop_top3(
    N=90,
    P=42,
    K=43,
    temperature=20.88,
    humidity=82.00,
    ph=6.50,
    rainfall=202.93
)

from google.colab import drive
drive.mount('/content/drive')

from google.colab import drive
drive.mount('/content/drive')

import os

base_folder = '/content/drive/MyDrive'

print("Searching for .keras model files...\n")

found_models = []

for root, folders, files in os.walk(base_folder):
    for file in files:
        if file.endswith('.keras'):
            full_path = os.path.join(root, file)
            found_models.append(full_path)
            print(full_path)

if len(found_models) == 0:
    print("No .keras model files were found.")

import os

project_folder = '/content/drive/MyDrive/ANN_Crop_Project'
os.makedirs(project_folder, exist_ok=True)

checkpoint = keras.callbacks.ModelCheckpoint(
    filepath=project_folder + '/final_crop_recommendation_ann.keras',
    monitor='val_loss',
    save_best_only=True,
    verbose=1
)

from google.colab import drive
drive.mount('/content/drive')

checkpoint = keras.callbacks.ModelCheckpoint(
    filepath=project_folder + '/final_crop_recommendation_ann.keras',
    monitor='val_loss',
    save_best_only=True,
    verbose=1
)

early_stopping = keras.callbacks.EarlyStopping(
    monitor='val_loss',
    patience=12,
    restore_best_weights=True
)

history = model.fit(

    X_train_scaled,
    y_train_encoded,

    validation_data=(
        X_val_scaled,
        y_val_encoded
    ),

    epochs=150,
    batch_size=32,

    callbacks=[
        early_stopping,
        checkpoint
    ],

    verbose=1
)

model.save(
    project_folder + '/final_crop_recommendation_ann.keras'
)

print("Final ANN saved permanently!")

train_data = X_train.copy()
train_data['label'] = y_train

validation_data = X_val.copy()
validation_data['label'] = y_val

test_data = X_test.copy()
test_data['label'] = y_test

train_data.to_csv(
    project_folder + '/training_data.csv',
    index=False
)

validation_data.to_csv(
    project_folder + '/validation_data.csv',
    index=False
)

test_data.to_csv(
    project_folder + '/testing_data.csv',
    index=False
)

df.to_csv(
    project_folder + '/Crop_recommendation.csv',
    index=False
)

print(os.listdir(project_folder))

print(
    "ANN model:",
    os.path.exists(
        project_folder + '/final_crop_recommendation_ann.keras'
    )
)

print(
    "Scaler:",
    os.path.exists(
        project_folder + '/crop_scaler.pkl'
    )
)

print(
    "Label encoder:",
    os.path.exists(
        project_folder + '/crop_label_encoder.pkl'
    )
)

from sklearn.preprocessing import StandardScaler
import joblib

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)
X_test_scaled = scaler.transform(X_test)

joblib.dump(
    scaler,
    project_folder + '/crop_scaler.pkl'
)

print("Scaler saved!")

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

y_train_encoded = label_encoder.fit_transform(y_train)
y_val_encoded = label_encoder.transform(y_val)
y_test_encoded = label_encoder.transform(y_test)

joblib.dump(
    label_encoder,
    project_folder + '/crop_label_encoder.pkl'
)

print("Label encoder saved!")

loaded_model = keras.models.load_model(
    project_folder + '/final_crop_recommendation_ann.keras'
)

loaded_scaler = joblib.load(
    project_folder + '/crop_scaler.pkl'
)

loaded_encoder = joblib.load(
    project_folder + '/crop_label_encoder.pkl'
)

print("Everything loaded successfully!")

loaded_model.summary()

!pip install -q gradio

import gradio as gr
import pandas as pd
import numpy as np
import joblib

from tensorflow import keras
from google.colab import drive

drive.mount('/content/drive')

project_folder = '/content/drive/MyDrive/ANN_Crop_Project'

model = keras.models.load_model(
    project_folder + '/final_crop_recommendation_ann.keras'
)

scaler = joblib.load(
    project_folder + '/crop_scaler.pkl'
)

label_encoder = joblib.load(
    project_folder + '/crop_label_encoder.pkl'
)

print("✅ Model, scaler and label encoder loaded successfully!")

def predict_crop(
    nitrogen,
    phosphorus,
    potassium,
    temperature,
    humidity,
    ph,
    rainfall
):

    # -----------------------------------------
    # Check whether all input values are entered
    # -----------------------------------------

    values = [
        nitrogen,
        phosphorus,
        potassium,
        temperature,
        humidity,
        ph,
        rainfall
    ]

    if any(value is None for value in values):

        warning = """
        <div class="warning-card">
            ⚠️ Please enter values for all seven parameters
            before requesting a crop recommendation.
        </div>
        """

        return warning, {}


    # -----------------------------------------
    # Basic input validation
    # -----------------------------------------

    if (
        nitrogen < 0 or nitrogen > 140 or
        phosphorus < 5 or phosphorus > 145 or
        potassium < 5 or potassium > 205 or
        temperature < 8 or temperature > 44 or
        humidity < 14 or humidity > 100 or
        ph < 3.5 or ph > 10 or
        rainfall < 20 or rainfall > 300
    ):

        warning = """
        <div class="warning-card">
            ⚠️ One or more values are outside the approximate
            range represented in the training dataset.
            Please check the entered values.
        </div>
        """

        return warning, {}


    # -----------------------------------------
    # Create input dataframe
    # -----------------------------------------

    input_data = pd.DataFrame({
        'N': [nitrogen],
        'P': [phosphorus],
        'K': [potassium],
        'temperature': [temperature],
        'humidity': [humidity],
        'ph': [ph],
        'rainfall': [rainfall]
    })


    # -----------------------------------------
    # Apply training scaler
    # -----------------------------------------

    input_scaled = scaler.transform(input_data)


    # -----------------------------------------
    # ANN prediction
    # -----------------------------------------

    probabilities = model.predict(
        input_scaled,
        verbose=0
    )[0]


    # -----------------------------------------
    # Highest probability crop
    # -----------------------------------------

    predicted_index = np.argmax(probabilities)

    predicted_crop = label_encoder.inverse_transform(
        [predicted_index]
    )[0]

    confidence = probabilities[predicted_index] * 100


    # -----------------------------------------
    # Top 3 crop predictions
    # -----------------------------------------

    top3_indices = np.argsort(
        probabilities
    )[-3:][::-1]

    top3_results = {}

    for index in top3_indices:

        crop_name = label_encoder.inverse_transform(
            [index]
        )[0]

        top3_results[crop_name] = float(
            probabilities[index]
        )


    # -----------------------------------------
    # Confidence description
    # -----------------------------------------

    if confidence >= 90:
        confidence_text = "Very High Model Confidence"

    elif confidence >= 70:
        confidence_text = "High Model Confidence"

    elif confidence >= 50:
        confidence_text = "Moderate Model Confidence"

    else:
        confidence_text = "Low Model Confidence"


    # -----------------------------------------
    # Attractive output card
    # -----------------------------------------

    result_html = f"""
    <div class="result-card">

        <div class="result-icon">
            🌱
        </div>

        <div class="result-small-title">
            ANN RECOMMENDATION
        </div>

        <div class="recommended-label">
            Recommended Crop
        </div>

        <div class="crop-name">
            {predicted_crop.title()}
        </div>

        <div class="confidence-container">

            <div class="confidence-title">
                Model Confidence
            </div>

            <div class="confidence-value">
                {confidence:.2f}%
            </div>

            <div class="confidence-description">
                {confidence_text}
            </div>

        </div>

        <div class="result-note">
            Recommendation generated using soil nutrient
            and climatic conditions supplied by the user.
        </div>

    </div>
    """

    return result_html, top3_results

custom_css = """

/* Main app */

.gradio-container {
    max-width: 1100px !important;
    margin: auto !important;
}


/* Hero section */

.hero-section {
    background: linear-gradient(
        135deg,
        #1b5e20,
        #388e3c
    );

    padding: 32px;
    border-radius: 22px;
    text-align: center;
    color: white;
    margin-bottom: 22px;
}

.hero-icon {
    font-size: 55px;
}

.hero-title {
    font-size: 32px;
    font-weight: 700;
    margin-top: 5px;
}

.hero-subtitle {
    font-size: 16px;
    opacity: 0.95;
    margin-top: 8px;
}


/* Section titles */

.section-heading {
    font-size: 20px;
    font-weight: 650;
    margin-top: 12px;
    margin-bottom: 4px;
}


/* Information box */

.info-box {
    padding: 15px 18px;
    border-radius: 12px;
    background: #f1f8e9;
    border-left: 5px solid #66bb6a;
    margin-bottom: 18px;
}


/* Prediction button */

#predict-button {
    font-size: 18px !important;
    font-weight: 650 !important;
    min-height: 52px !important;
}


/* Recommendation card */

.result-card {

    background: linear-gradient(
        135deg,
        #f1f8e9,
        #e8f5e9
    );

    border: 2px solid #81c784;

    border-radius: 24px;

    padding: 30px;

    text-align: center;

    margin-top: 10px;
}

.result-icon {
    font-size: 48px;
}

.result-small-title {
    font-size: 12px;
    letter-spacing: 2px;
    color: #558b2f;
    font-weight: bold;
    margin-top: 5px;
}

.recommended-label {
    margin-top: 18px;
    font-size: 17px;
    color: #555;
}

.crop-name {
    font-size: 43px;
    color: #1b5e20;
    font-weight: 750;
    margin-top: 3px;
}

.confidence-container {
    margin: 22px auto 10px auto;
    padding: 16px;
    max-width: 350px;
    border-radius: 16px;
    background: white;
}

.confidence-title {
    font-size: 14px;
    color: #666;
}

.confidence-value {
    font-size: 30px;
    font-weight: bold;
    color: #2e7d32;
}

.confidence-description {
    font-size: 13px;
    color: #558b2f;
}

.result-note {
    margin-top: 18px;
    font-size: 13px;
    color: #666;
}


/* Warning */

.warning-card {

    padding: 20px;

    border-radius: 14px;

    background: #fff8e1;

    border: 2px solid #ffca28;

    color: #6d4c41;

    text-align: center;

    font-size: 16px;
}


/* Footer */

.footer-box {
    text-align: center;
    font-size: 12px;
    color: #777;
    margin-top: 25px;
}

"""

with gr.Blocks(

    theme=gr.themes.Soft(
        primary_hue="green"
    ),

    css=custom_css,

    title="ANN Crop Recommendation System"

) as app:


    # ==========================================
    # HERO SECTION
    # ==========================================

    gr.HTML(
        """
        <div class="hero-section">

            <div class="hero-icon">
                🌾
            </div>

            <div class="hero-title">
                Smart Crop Recommendation System
            </div>

            <div class="hero-subtitle">
                Artificial Neural Network Based
                Agricultural Decision Support System
            </div>

        </div>
        """
    )


    # ==========================================
    # INFORMATION
    # ==========================================

    gr.HTML(
        """
        <div class="info-box">

        <b>🌱 How to use the system:</b><br>

        Enter the soil nutrient values and climatic
        conditions of the agricultural area.

        The trained Artificial Neural Network will
        analyse the conditions and recommend the
        most suitable crop from 22 crop categories.

        </div>
        """
    )


    # ==========================================
    # SOIL NUTRIENTS
    # ==========================================

    gr.HTML(
        """
        <div class="section-heading">
            🧪 Soil Nutrient Parameters
        </div>
        """
    )


    with gr.Row():

        nitrogen = gr.Number(
            label="Nitrogen (N)",
            value=70,
            minimum=0,
            maximum=140,
            info="Approximate dataset range: 0–140"
        )

        phosphorus = gr.Number(
            label="Phosphorus (P)",
            value=50,
            minimum=5,
            maximum=145,
            info="Approximate dataset range: 5–145"
        )

        potassium = gr.Number(
            label="Potassium (K)",
            value=50,
            minimum=5,
            maximum=205,
            info="Approximate dataset range: 5–205"
        )


    # ==========================================
    # CLIMATIC CONDITIONS
    # ==========================================

    gr.HTML(
        """
        <div class="section-heading">
            🌦️ Climatic Conditions
        </div>
        """
    )


    with gr.Row():

        temperature = gr.Number(
            label="Temperature (°C)",
            value=25,
            minimum=8,
            maximum=44,
            info="Approximate dataset range: 8–44 °C"
        )

        humidity = gr.Number(
            label="Humidity (%)",
            value=70,
            minimum=14,
            maximum=100,
            info="Approximate dataset range: 14–100%"
        )


    # ==========================================
    # SOIL / WATER CONDITIONS
    # ==========================================

    gr.HTML(
        """
        <div class="section-heading">
            🌍 Soil & Rainfall Conditions
        </div>
        """
    )


    with gr.Row():

        ph = gr.Number(
            label="Soil pH",
            value=6.5,
            minimum=3.5,
            maximum=10,
            info="Approximate dataset range: 3.5–10"
        )

        rainfall = gr.Number(
            label="Rainfall (mm)",
            value=100,
            minimum=20,
            maximum=300,
            info="Approximate dataset range: 20–300 mm"
        )


    # ==========================================
    # BUTTONS
    # ==========================================

    with gr.Row():

        predict_button = gr.Button(
            "🌾 Analyse Conditions & Recommend Crop",
            variant="primary",
            elem_id="predict-button"
        )

        clear_button = gr.ClearButton(
            value="🔄 Clear Inputs"
        )


    # ==========================================
    # RESULTS
    # ==========================================

    gr.HTML(
        """
        <div class="section-heading">
            🎯 ANN Recommendation
        </div>
        """
    )


    result_output = gr.HTML()


    gr.HTML(
        """
        <div class="section-heading">
            📊 Top 3 Model Predictions
        </div>
        """
    )


    probability_output = gr.Label(
        label="Prediction probabilities",
        num_top_classes=3
    )


    # ==========================================
    # EXAMPLE INPUTS
    # ==========================================

    gr.HTML(
        """
        <div class="section-heading">
            🧾 Example Conditions
        </div>

        <div style="
            font-size: 13px;
            color: #666;
            margin-bottom: 10px;
        ">
            Click an example below to automatically
            fill the input fields.
        </div>
        """
    )


    examples = gr.Examples(

        examples=[

            [
                90,
                42,
                43,
                20.88,
                82.00,
                6.50,
                202.93
            ],

            [
                100,
                18,
                30,
                27.0,
                80.0,
                6.2,
                100.0
            ],

            [
                20,
                30,
                20,
                25.0,
                60.0,
                6.5,
                70.0
            ]

        ],

        inputs=[
            nitrogen,
            phosphorus,
            potassium,
            temperature,
            humidity,
            ph,
            rainfall
        ],

        label="Example environmental conditions"
    )


    # ==========================================
    # BUTTON CONNECTION
    # ==========================================

    predict_button.click(

        fn=predict_crop,

        inputs=[
            nitrogen,
            phosphorus,
            potassium,
            temperature,
            humidity,
            ph,
            rainfall
        ],

        outputs=[
            result_output,
            probability_output
        ]
    )


    # ==========================================
    # CLEAR BUTTON
    # ==========================================

    clear_button.add(
        [
            nitrogen,
            phosphorus,
            potassium,
            temperature,
            humidity,
            ph,
            rainfall,
            result_output,
            probability_output
        ]
    )


    # ==========================================
    # FOOTER
    # ==========================================

    gr.HTML(
        """
        <div class="footer-box">

        Artificial Neural Network Crop Recommendation Project<br>

        Inputs:
        N • P • K • Temperature • Humidity • pH • Rainfall

        <br><br>

        <b>Note:</b>
        This system is an academic machine-learning
        prototype and should not replace professional
        agricultural or field-specific advice.

        </div>
        """
    )

app.launch(
    share=True
)

!pip install -q gradio

import gradio as gr
import pandas as pd
import numpy as np
import joblib

from tensorflow import keras
from google.colab import drive

drive.mount('/content/drive')

project_folder = '/content/drive/MyDrive/ANN_Crop_Project'

model = keras.models.load_model(
    project_folder + '/final_crop_recommendation_ann.keras'
)

scaler = joblib.load(
    project_folder + '/crop_scaler.pkl'
)

label_encoder = joblib.load(
    project_folder + '/crop_label_encoder.pkl'
)

print("✅ Model, scaler and label encoder loaded successfully!")

def predict_crop(
    nitrogen,
    phosphorus,
    potassium,
    temperature,
    humidity,
    ph,
    rainfall
):

    # -----------------------------------------
    # Check whether all input values are entered
    # -----------------------------------------

    values = [
        nitrogen,
        phosphorus,
        potassium,
        temperature,
        humidity,
        ph,
        rainfall
    ]

    if any(value is None for value in values):

        warning = """
        <div class="warning-card">
            ⚠️ Please enter values for all seven parameters
            before requesting a crop recommendation.
        </div>
        """

        return warning, {}


    # -----------------------------------------
    # Basic input validation
    # -----------------------------------------

    if (
        nitrogen < 0 or nitrogen > 140 or
        phosphorus < 5 or phosphorus > 145 or
        potassium < 5 or potassium > 205 or
        temperature < 8 or temperature > 44 or
        humidity < 14 or humidity > 100 or
        ph < 3.5 or ph > 10 or
        rainfall < 20 or rainfall > 300
    ):

        warning = """
        <div class="warning-card">
            ⚠️ One or more values are outside the approximate
            range represented in the training dataset.
            Please check the entered values.
        </div>
        """

        return warning, {}


    # -----------------------------------------
    # Create input dataframe
    # -----------------------------------------

    input_data = pd.DataFrame({
        'N': [nitrogen],
        'P': [phosphorus],
        'K': [potassium],
        'temperature': [temperature],
        'humidity': [humidity],
        'ph': [ph],
        'rainfall': [rainfall]
    })


    # -----------------------------------------
    # Apply training scaler
    # -----------------------------------------

    input_scaled = scaler.transform(input_data)


    # -----------------------------------------
    # ANN prediction
    # -----------------------------------------

    probabilities = model.predict(
        input_scaled,
        verbose=0
    )[0]


    # -----------------------------------------
    # Highest probability crop
    # -----------------------------------------

    predicted_index = np.argmax(probabilities)

    predicted_crop = label_encoder.inverse_transform(
        [predicted_index]
    )[0]

    confidence = probabilities[predicted_index] * 100


    # -----------------------------------------
    # Top 3 crop predictions
    # -----------------------------------------

    top3_indices = np.argsort(
        probabilities
    )[-3:][::-1]

    top3_results = {}

    for index in top3_indices:

        crop_name = label_encoder.inverse_transform(
            [index]
        )[0]

        top3_results[crop_name] = float(
            probabilities[index]
        )


    # -----------------------------------------
    # Confidence description
    # -----------------------------------------

    if confidence >= 90:
        confidence_text = "Very High Model Confidence"

    elif confidence >= 70:
        confidence_text = "High Model Confidence"

    elif confidence >= 50:
        confidence_text = "Moderate Model Confidence"

    else:
        confidence_text = "Low Model Confidence"


    # -----------------------------------------
    # Attractive output card
    # -----------------------------------------

    result_html = f"""
    <div class="result-card">

        <div class="result-icon">
            🌱
        </div>

        <div class="result-small-title">
            ANN RECOMMENDATION
        </div>

        <div class="recommended-label">
            Recommended Crop
        </div>

        <div class="crop-name">
            {predicted_crop.title()}
        </div>

        <div class="confidence-container">

            <div class="confidence-title">
                Model Confidence
            </div>

            <div class="confidence-value">
                {confidence:.2f}%
            </div>

            <div class="confidence-description">
                {confidence_text}
            </div>

        </div>

        <div class="result-note">
            Recommendation generated using soil nutrient
            and climatic conditions supplied by the user.
        </div>

    </div>
    """

    return result_html, top3_results

def predict_crop(
    nitrogen,
    phosphorus,
    potassium,
    temperature,
    humidity,
    ph,
    rainfall
):

    # -----------------------------------------
    # Check whether all input values are entered
    # -----------------------------------------

    values = [
        nitrogen,
        phosphorus,
        potassium,
        temperature,
        humidity,
        ph,
        rainfall
    ]

    if any(value is None for value in values):

        warning = """
        <div class="warning-card">
            ⚠️ Please enter values for all seven parameters
            before requesting a crop recommendation.
        </div>
        """

        return warning, {}


    # -----------------------------------------
    # Basic input validation
    # -----------------------------------------

    if (
        nitrogen < 0 or nitrogen > 140 or
        phosphorus < 5 or phosphorus > 145 or
        potassium < 5 or potassium > 205 or
        temperature < 8 or temperature > 44 or
        humidity < 14 or humidity > 100 or
        ph < 3.5 or ph > 10 or
        rainfall < 20 or rainfall > 300
    ):

        warning = """
        <div class="warning-card">
            ⚠️ One or more values are outside the approximate
            range represented in the training dataset.
            Please check the entered values.
        </div>
        """

        return warning, {}


    # -----------------------------------------
    # Create input dataframe
    # -----------------------------------------

    input_data = pd.DataFrame({
        'N': [nitrogen],
        'P': [phosphorus],
        'K': [potassium],
        'temperature': [temperature],
        'humidity': [humidity],
        'ph': [ph],
        'rainfall': [rainfall]
    })


    # -----------------------------------------
    # Apply training scaler
    # -----------------------------------------

    input_scaled = scaler.transform(input_data)


    # -----------------------------------------
    # ANN prediction
    # -----------------------------------------

    probabilities = model.predict(
        input_scaled,
        verbose=0
    )[0]


    # -----------------------------------------
    # Highest probability crop
    # -----------------------------------------

    predicted_index = np.argmax(probabilities)

    predicted_crop = label_encoder.inverse_transform(
        [predicted_index]
    )[0]

    confidence = probabilities[predicted_index] * 100


    # -----------------------------------------
    # Top 3 crop predictions
    # -----------------------------------------

    top3_indices = np.argsort(
        probabilities
    )[-3:][::-1]

    top3_results = {}

    for index in top3_indices:

        crop_name = label_encoder.inverse_transform(
            [index]
        )[0]

        top3_results[crop_name] = float(
            probabilities[index]
        )


    # -----------------------------------------
    # Confidence description
    # -----------------------------------------

    if confidence >= 90:
        confidence_text = "Very High Model Confidence"

    elif confidence >= 70:
        confidence_text = "High Model Confidence"

    elif confidence >= 50:
        confidence_text = "Moderate Model Confidence"

    else:
        confidence_text = "Low Model Confidence"


    # -----------------------------------------
    # Attractive output card
    # -----------------------------------------

    result_html = f"""
    <div class="result-card">

        <div class="result-icon">
            🌱
        </div>

        <div class="result-small-title">
            ANN RECOMMENDATION
        </div>

        <div class="recommended-label">
            Recommended Crop
        </div>

        <div class="crop-name">
            {predicted_crop.title()}
        </div>

        <div class="confidence-container">

            <div class="confidence-title">
                Model Confidence
            </div>

            <div class="confidence-value">
                {confidence:.2f}%
            </div>

            <div class="confidence-description">
                {confidence_text}
            </div>

        </div>

        <div class="result-note">
            Recommendation generated using soil nutrient
            and climatic conditions supplied by the user.
        </div>

    </div>
    """

    return result_html, top3_results

custom_css = """

/* Main app */

.gradio-container {
    max-width: 1100px !important;
    margin: auto !important;
}


/* Hero section */

.hero-section {
    background: linear-gradient(
        135deg,
        #1b5e20,
        #388e3c
    );

    padding: 32px;
    border-radius: 22px;
    text-align: center;
    color: white;
    margin-bottom: 22px;
}

.hero-icon {
    font-size: 55px;
}

.hero-title {
    font-size: 32px;
    font-weight: 700;
    margin-top: 5px;
}

.hero-subtitle {
    font-size: 16px;
    opacity: 0.95;
    margin-top: 8px;
}


/* Section titles */

.section-heading {
    font-size: 20px;
    font-weight: 650;
    margin-top: 12px;
    margin-bottom: 4px;
}


/* Information box */

.info-box {
    padding: 15px 18px;
    border-radius: 12px;
    background: #f1f8e9;
    border-left: 5px solid #66bb6a;
    margin-bottom: 18px;
}


/* Prediction button */

#predict-button {
    font-size: 18px !important;
    font-weight: 650 !important;
    min-height: 52px !important;
}


/* Recommendation card */

.result-card {

    background: linear-gradient(
        135deg,
        #f1f8e9,
        #e8f5e9
    );

    border: 2px solid #81c784;

    border-radius: 24px;

    padding: 30px;

    text-align: center;

    margin-top: 10px;
}

.result-icon {
    font-size: 48px;
}

.result-small-title {
    font-size: 12px;
    letter-spacing: 2px;
    color: #558b2f;
    font-weight: bold;
    margin-top: 5px;
}

.recommended-label {
    margin-top: 18px;
    font-size: 17px;
    color: #555;
}

.crop-name {
    font-size: 43px;
    color: #1b5e20;
    font-weight: 750;
    margin-top: 3px;
}

.confidence-container {
    margin: 22px auto 10px auto;
    padding: 16px;
    max-width: 350px;
    border-radius: 16px;
    background: white;
}

.confidence-title {
    font-size: 14px;
    color: #666;
}

.confidence-value {
    font-size: 30px;
    font-weight: bold;
    color: #2e7d32;
}

.confidence-description {
    font-size: 13px;
    color: #558b2f;
}

.result-note {
    margin-top: 18px;
    font-size: 13px;
    color: #666;
}


/* Warning */

.warning-card {

    padding: 20px;

    border-radius: 14px;

    background: #fff8e1;

    border: 2px solid #ffca28;

    color: #6d4c41;

    text-align: center;

    font-size: 16px;
}


/* Footer */

.footer-box {
    text-align: center;
    font-size: 12px;
    color: #777;
    margin-top: 25px;
}

"""

with gr.Blocks(

    theme=gr.themes.Soft(
        primary_hue="green"
    ),

    css=custom_css,

    title="ANN Crop Recommendation System"

) as app:


    # ==========================================
    # HERO SECTION
    # ==========================================

    gr.HTML(
        """
        <div class="hero-section">

            <div class="hero-icon">
                🌾
            </div>

            <div class="hero-title">
                Smart Crop Recommendation System
            </div>

            <div class="hero-subtitle">
                Artificial Neural Network Based
                Agricultural Decision Support System
            </div>

        </div>
        """
    )


    # ==========================================
    # INFORMATION
    # ==========================================

    gr.HTML(
        """
        <div class="info-box">

        <b>🌱 How to use the system:</b><br>

        Enter the soil nutrient values and climatic
        conditions of the agricultural area.

        The trained Artificial Neural Network will
        analyse the conditions and recommend the
        most suitable crop from 22 crop categories.

        </div>
        """
    )


    # ==========================================
    # SOIL NUTRIENTS
    # ==========================================

    gr.HTML(
        """
        <div class="section-heading">
            🧪 Soil Nutrient Parameters
        </div>
        """
    )


    with gr.Row():

        nitrogen = gr.Number(
            label="Nitrogen (N)",
            value=70,
            minimum=0,
            maximum=140,
            info="Approximate dataset range: 0–140"
        )

        phosphorus = gr.Number(
            label="Phosphorus (P)",
            value=50,
            minimum=5,
            maximum=145,
            info="Approximate dataset range: 5–145"
        )

        potassium = gr.Number(
            label="Potassium (K)",
            value=50,
            minimum=5,
            maximum=205,
            info="Approximate dataset range: 5–205"
        )


    # ==========================================
    # CLIMATIC CONDITIONS
    # ==========================================

    gr.HTML(
        """
        <div class="section-heading">
            🌦️ Climatic Conditions
        </div>
        """
    )


    with gr.Row():

        temperature = gr.Number(
            label="Temperature (°C)",
            value=25,
            minimum=8,
            maximum=44,
            info="Approximate dataset range: 8–44 °C"
        )

        humidity = gr.Number(
            label="Humidity (%)",
            value=70,
            minimum=14,
            maximum=100,
            info="Approximate dataset range: 14–100%"
        )


    # ==========================================
    # SOIL / WATER CONDITIONS
    # ==========================================

    gr.HTML(
        """
        <div class="section-heading">
            🌍 Soil & Rainfall Conditions
        </div>
        """
    )


    with gr.Row():

        ph = gr.Number(
            label="Soil pH",
            value=6.5,
            minimum=3.5,
            maximum=10,
            info="Approximate dataset range: 3.5–10"
        )

        rainfall = gr.Number(
            label="Rainfall (mm)",
            value=100,
            minimum=20,
            maximum=300,
            info="Approximate dataset range: 20–300 mm"
        )


    # ==========================================
    # BUTTONS
    # ==========================================

    with gr.Row():

        predict_button = gr.Button(
            "🌾 Analyse Conditions & Recommend Crop",
            variant="primary",
            elem_id="predict-button"
        )

        clear_button = gr.ClearButton(
            value="🔄 Clear Inputs"
        )


    # ==========================================
    # RESULTS
    # ==========================================

    gr.HTML(
        """
        <div class="section-heading">
            🎯 ANN Recommendation
        </div>
        """
    )


    result_output = gr.HTML()


    gr.HTML(
        """
        <div class="section-heading">
            📊 Top 3 Model Predictions
        </div>
        """
    )


    probability_output = gr.Label(
        label="Prediction probabilities",
        num_top_classes=3
    )


    # ==========================================
    # EXAMPLE INPUTS
    # ==========================================

    gr.HTML(
        """
        <div class="section-heading">
            🧾 Example Conditions
        </div>

        <div style="
            font-size: 13px;
            color: #666;
            margin-bottom: 10px;
        ">
            Click an example below to automatically
            fill the input fields.
        </div>
        """
    )


    examples = gr.Examples(

        examples=[

            [
                90,
                42,
                43,
                20.88,
                82.00,
                6.50,
                202.93
            ],

            [
                100,
                18,
                30,
                27.0,
                80.0,
                6.2,
                100.0
            ],

            [
                20,
                30,
                20,
                25.0,
                60.0,
                6.5,
                70.0
            ]

        ],

        inputs=[
            nitrogen,
            phosphorus,
            potassium,
            temperature,
            humidity,
            ph,
            rainfall
        ],

        label="Example environmental conditions"
    )


    # ==========================================
    # BUTTON CONNECTION
    # ==========================================

    predict_button.click(

        fn=predict_crop,

        inputs=[
            nitrogen,
            phosphorus,
            potassium,
            temperature,
            humidity,
            ph,
            rainfall
        ],

        outputs=[
            result_output,
            probability_output
        ]
    )


    # ==========================================
    # CLEAR BUTTON
    # ==========================================

    clear_button.add(
        [
            nitrogen,
            phosphorus,
            potassium,
            temperature,
            humidity,
            ph,
            rainfall,
            result_output,
            probability_output
        ]
    )


    # ==========================================
    # FOOTER
    # ==========================================

    gr.HTML(
        """
        <div class="footer-box">

        Artificial Neural Network Crop Recommendation Project<br>

        Inputs:
        N • P • K • Temperature • Humidity • pH • Rainfall

        <br><br>

        <b>Note:</b>
        This system is an academic machine-learning
        prototype and should not replace professional
        agricultural or field-specific advice.

        </div>
        """
    )

app.launch(
    share=True
)

import gradio as gr

print("Gradio version:", gr.__version__)

import sys

!{sys.executable} -m pip install --force-reinstall --no-cache-dir "gradio==6.3.0"

import gradio as gr

print(gr.__version__)

try:
    app.close()
except:
    pass

!pip uninstall -y gradio gradio_client
!pip install -q gradio==6.3.0

